#! /bin/sh

case "$(readlink -f /proc/$$/exe)" in
	*)
		sh="$(readlink -f /proc/$$/exe)"
		echo "using shell : $sh"
	;;
esac

jailToolsPath=ScriptPath

uid=$(id -u)

if [ "$jailToolsPath" = "ScriptPath" ]; then
	exit 1 # this script has to be installed to be used.
fi

showHelp() {
	echo "Usage:"
	echo "  $(basename $0) <command> [command options]"
	echo
	echo "Available commands :"
	printf "    help, h\t\t\tdisplay this help\n"
	printf "    new, create\t\t\tcreate a new jailTools directory\n"
	printf "    cp, cpDep\t\t\tcopy files or directories (with their shared object dependencies) into the jailTools\n"
	printf "    start, stop, shell\t\tthese are jailTools specific commands to be used inside a jailTools directory only.\n"
}

if [ "$1" = "" ]; then
	showHelp
	exit 0
fi

case $1 in
	help|h)
		showHelp
		exit 0
	;;

	new|create)
		shift 1
		$sh $jailToolsPath/newJail.sh $@
		exit 0
	;;

	cp|cpDep)
		shift 1
		if [ -d ./root ] && [ -d ./run ] && [ -f ./startRoot.sh ] && [ -f ./rootCustomConfig.sh ]; then
			$sh $jailToolsPath/cpDep.sh $PWD $@
		else
			$sh $jailToolsPath/cpDep.sh $@
		fi
		exit 0
	;;

	start|stop|shell)

		if [ -d ./root ] && [ -d ./run ] && [ -f ./startRoot.sh ] && [ -f ./rootCustomConfig.sh ]; then
			if [ "$uid" != "0" ]; then
				echo "It is necessary to be root to run these commands"
				exit 1
			fi
			$sh ./startRoot.sh $1
		else
			echo "These commands are only valid inside the root of a jail created by jailTools"
			exit 1
		fi

		exit 0
	;;

	daemon)
		if [ -d ./root ] && [ -d ./run ] && [ -f ./startRoot.sh ] && [ -f ./rootCustomConfig.sh ]; then
			if [ "$uid" != "0" ]; then
				echo "It is necessary to be root to run these commands"
				exit 1
			fi
			nohup $sh ./startRoot.sh 'daemon' >/dev/null 2>/dev/null 0<&- &>/dev/null &
			#if [ "$?" != "0" ]; then echo "There was an error starting the daemon, it may already be running."; fi
		else
			echo "These commands are only valid inside the root of a jail created by jailTools"
			exit 1
		fi

		exit 0
	;;

	*)
		echo "Invalid command \`$1'"
		exit 1
	;;
esac
