#! /bin/sh

case "$(readlink -f /proc/$$/exe)" in
	*dash)
		echo "We don't support dash"
		exit 1
	;;

	*)
		sh="$(readlink -f /proc/$$/exe)"
		echo "using shell : $sh"
	;;
esac

jailToolsPath=ScriptPath

uid=$UID

if [ "$jailToolsPath" = "ScriptPath" ]; then
	exit 1 # this script has to be installed to be used.
fi

function showHelp() {
	echo "Usage:"
	echo -e "  $(basename $0) <command> [command options]"
	echo
	echo "Available commands :"
	echo -e "    help, h\t\t\tdisplay this help"
	echo -e "    new, create\t\t\tcreate a new jailTools directory"
	echo -e "    cp, cpDep\t\t\tcopy files or directories (with their shared object dependencies) into the jailTools"
	echo -e "    start, stop, shell\t\tthese are jailTools specific commands to be used inside a jailTools directory only."
}

if [ "$1" = "" ]; then
	showHelp
	exit 0
fi

case $1 in
	help|h)
		showHelp
		exit 0
	;;

	new|create)
		shift 1
		$sh $jailToolsPath/newJail.sh $@
		exit 0
	;;

	cp|cpDep)
		shift 1
		if [ -d ./root ] && [ -d ./run ] && [ -f ./startRoot.sh ] && [ -f ./rootCustomConfig.sh ]; then
			$sh $jailToolsPath/cpDep.sh . $@
		else
			$sh $jailToolsPath/cpDep.sh $@
		fi
		exit 0
	;;

	start|stop|shell)

		if [ -d ./root ] && [ -d ./run ] && [ -f ./startRoot.sh ] && [ -f ./rootCustomConfig.sh ]; then
			if [ "$uid" != "0" ]; then
				echo "It is necessary to be root to run these commands"
				exit 1
			fi
			$sh ./startRoot.sh $1
		else
			echo "These commands are only valid inside the root of a jail created by jailTools"
			exit 1
		fi

		exit 0
	;;

	*)
		echo "Invalid command \`$1'"
		exit 1
	;;
esac
