JailTools - helper script for creating jails
============================================

What is JailTools?
------------------

Jailtools is a toolkit for easily creating a jail for your services using chroot and namespaces. It provides a slim OS-level virtualization solution for the GNU/linux operating system.


Purpose
-------

JailTools makes it easy to create chroots for any purpose.
It has tools for copying applications and libraries to the jail, so as to also copy
the shared objects they depend on to run correctly.
JailTools creates a minimal filesystem (about 6MB in size) which is meant to include
only the bare minimum for applications or libraries to do their job. This way, in case
the service is compromized, the adversary will only get access to that filesystem rather
than the host system directly.


Content
--------

*The main scripts*
~~~~~~~~~~~~~~~~~~
There are 3 useful scripts :

. *jailtools* - *jtools* - *jt*

        (jtools and jt are just symbolic links to jailtools)
        This is a super script that can be used to call the other 2 scripts and
        do the various tasks related to jailTools directories.
        This is the only script you will ever need to use.

. *newJail.sh*

        Used to create new jails (as the name implies).

. *cpDep.sh*

        Used to copy binaries or libraries to the jail and it does
        it's best to copy dependencies (shared objects) with it too.


Compilation and Installation
--------

Quick steps :
0. install requirements: git, gcc
1. get the source code with 'git clone https://github.com/nniro/jailTools.git'
2. compile and install musl and busybox. This is done automatically by calling `make'
3. install the super script with install.sh
...
profit!
*

Explanation, step by step:
--------------------------------------

Step 1:
Get jailTools from the git repository:

        'git clone https://github.com/nniro/jailTools.git'

This will download the repository to the directory 'jailTools'.

Step 2:
The project relies on musl (libc) and busybox. The latter provides the underlying filesystem shell and commands inside each jail.
Both of these dependencies are automatically cloned by the Makefile process.
We don't use already installed versions because we want statically linked versions of both of these to save space.

To compile, just run 'make'.
This will compile musl, compile a statically linked busybox using the musl libc.

If you want to install jailTools system wide, for all users, then move jailTools folder to '/opt':

        'sudo mv ~/jailTools /opt/jailTools'

And change ownership to root:

        'sudo chown root:root -R /opt/jailTools'

Step 3:
The installation script `install.sh' will copy the super script `jailtools' to
a location of your choice. It only installs the super script, not the whole jailTools
directory. It sets up the super script with the path of the project's git repository directory
so it could stay in any place you want.

If you want to use jailTools for your user only, just clone the git repository, compile and
do this:

        sh ./install.sh ~/bin

This will install the super script inside your user's bin directory.
Make sure that you have ~/bin in your "PATH" environment variable.

In case you want to make the project available for all users on the system, do this :

       sudo sh ./install.sh /opt/bin

This will install the super script to the path /opt/bin. The script `install.sh' needs to be executed from the location
where the jailTools scripts reside so the references are done correctly inside the super script `jailtools'.


*How to use the super script jailtools*
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The usage is very similar to using the scripts newJail.sh and cpDep.sh directly except these
are set as commands inside the super script. Here is a list of the available commands :

    new, create                 create a new jailTools directory
    cp, cpDep                   copy files or directories (with their shared object dependencies) into the jailTools
    start, stop, shell          these are jailTools specific commands to be used inside a jailTools directory only.


Tutorial
--------

*How to create a new jail*
~~~~~~~~~~~~~~~~~~~~
This is how you can create a new jail :

(This is done as a normal user, no need to be privileged)
----
jt new <path and name> <optional jail's main username> <optional jail's main group>
----

both internal username and group are actually for inside the jail itself, they
will be added to /etc/\{passwd,shadow\} and /etc/group respectively, inside the
chroot. The main user will be exactly the same UID as the user that created
the jail, same goes for the group. If they are not explicitely added, they will be
created with the same name as the jail.

The jail name is simply a directory of that name that will be created and any
reference of the jail internally is done with that name.
The jail name will be used as a name for the directory created containing the jail, and any
reference of the jail internally is done with that name.

Example :
----
jt new example foo bar
----

This will create a new directory called example containing the jail and once running, the user's
UID and GID will be mapped to foo and bar respectively. Inside the jail directory
there are 3 notable scripts :
. startRoot.sh (don't run this directly, use the super script jailtools)
. rootCustomConfig.sh (where you place your configuration and custom scripting)
. update.sh (this contains the files which are copied by the 'cp/cpDep' command so you can reproduce
and update your jail)
The script startRoot.sh is not meant to be edited, only make your changes in the script
rootCustomConfig.sh. 
The script startRoot.sh is not meant to be edited.  Make your changes in the script rootCustomConfig.sh. 

As is, the system creates a jail with only basic apps and a shell.

*The generated jail*
~~~~~~~~~~~~~~~~~~~~
A newly created jail includes 2 ways to start the chroot : 

sudo jt start

        Used to start your services and such. By default it does the same
        as the command shell.

sudo jt shell

        Used to get shell access to do your commands inside the jail. This
        also allows you to enter an already started jail.

////
sudo jt shell

this will move you inside the chroot filesystem in which you can
do basic commands.
////

Now, if you want to add more applications to the jail, you have to
use jailtools's cp or cpDep command.

Here we show how to copy the application telnet to the jail :

----
(this is done inside the jail directory itself)
jt cp /usr/bin /usr/bin/telnet
----

Here's what the arguments mean :

* /usr/bin

        The first path is actually the destination path *inside* the
        jail that you want to copy your binary to. We could have put /bin if we wanted
        or any path you want (as long as you take care of setting the PATH correctly
        in the jail).

* /usr/bin/telnet

        This is the path on your base system for the telnet application, which, in our
        case is in our /usr/bin directory.

cpDep will check all shared object dependencies that telnet requires to run
and copy them along with the binary itself. This way, you will be able to run
the application without doing any more work than that.

*How to Customize the jail*
~~~~~~~~~~~~~~~~~~~~~~~~~~~

There are 4 vectors of customization for jails. Each
in their own section in rootCustomConfig.sh.

The 4 sections in rootCustomConfig.sh :

. The configuration variables

        These are used to toggle features provided in the jail and set various values
        for setting for example the firewall.

. The mount points

        These are used specifically to mount external directories inside the jail itself,
        making the files/directories accessible to the jailed applications. There are 3 kinds
        of mount points each with their section.

. the functions

        These are used to customize firewall rules, mount extra files (those that are out of
        scope of the mount points section) and set up your own start instructions so the
        jail can run the service you want.

. startRoot.sh CUI commands

        Use this to set up your own startRoot.sh commands.

Tips and Tricks
---------------

*shorewall specific*
~~~~~~~~~~~~~~~~~~~~

how to open a port
^^^^^^^^^^^^^^^^^^
Shorewall custom INBOUND configuration : 
in rootCustomConfig.sh, in the function prepCustom, add these lines :

****
        cat >> $firewallPath/rules.d/$bridgeName.rules << EOF
ACCEPT  fw      $firewallZoneName       tcp     10922
DNAT    lan     $firewallZoneName:$ipInt tcp    10922
EOF
****

this is an example where we open the port 10922 for access from the
localhost and also the lan network. Notice that for the lan network (external
to the main host) we have to use a DNAT to our internal chroot.

how to prepare shorewall for jailTools
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

With shorewall, jailTools adds it's changes to a directory ending with '.d' like 'rules.d'.
These are not standard issue with shorewall, to make use of their content, it is necessary to
add a single line in all the configuration files that potentially will get extra configurations
in these. (As of this writing, these configuration files need modifications : 
        zones, interfaces, policy and snat, we create one for rules too strictly as a service for
        the user as jailtools does not add anything to it directly).

Here's how you can actually make your configuration file load all the content of the 'x.d' directory
(for example here zones -> zones.d).

----
SHELL cat /etc/shorewall/zones.d/*.zones 2> /dev/null || true
----

And that's it, this loads all the .zones files in zones.d and the last part of the instruction is to ensure
everything works correctly even if the directory is empty.

It's exactly the same line for all the other configuration files except the 2 occurences of 'zones' which need
to be changed to the configuration's name : like rules.d/*.rules

Noteworthy : in pretty much all configuration files you can add this line at the end, except for policy.
This one will need to have the inclusion before the last line that rejects everything.
