#! /bin/sh

case "$(readlink -f /proc/$$/exe)" in
	*busybox)
		sh="$(readlink -f /proc/$$/exe) sh"
		echo "using shell : $sh"
	;;

	*)
		sh="$(readlink -f /proc/$$/exe)"
		echo "using shell : $sh"
	;;
esac

jailToolsPath=ScriptPath

uid=$(id -u)

. $jailToolsPath/scripts/utils.sh # detectJail

if [ "$jailToolsPath" = "ScriptPath" ]; then
	exit 1 # this script has to be installed to be used.
fi

if [ ! -e $jailToolsPath/../busybox/busybox ]; then
	echo "Please run 'make' in \`$ownPath' to compile the necessary dependencies first"
	exit 1
fi

showHelp() {
	echo "Usage:"
	echo "  $(basename $0) <command> [command options]"
	echo
	echo "Available commands :"
	printf "    help, h\t\t\tdisplay this help\n"
	printf "    new, create\t\t\tcreate a new jailTools directory\n"
	printf "    cp, cpDep\t\t\tcopy files or directories (with their shared object dependencies) into the jailTools\n"
	printf "    start, stop, shell\t\tthese are jailTools specific commands to be used inside a jailTools directory only.\n"
}

cmd=$1
if [ "$cmd" = "" ]; then
	showHelp
	exit 0
fi
shift

case $cmd in
	help|h)
		showHelp
	;;

	new|create)
		$sh $jailToolsPath/scripts/newJail.sh $@
		exit $?
	;;

	cp|cpDep)
		if [ -d ./root ] && [ -d ./run ] && [ -f ./startRoot.sh ] && [ -f ./rootCustomConfig.sh ]; then
			$sh $jailToolsPath/scripts/cpDep.sh $PWD $@
		else
			$sh $jailToolsPath/scripts/cpDep.sh $@
		fi
		exit $?
	;;

	start|stop|shell)
		if [ "$1" = "" ]; then
			jPath="."
		else
			if [ -e $1 ]; then
				jPath="$1"
				shift
			fi
		fi

		if detectJail $jPath; then
			$sh $jPath/startRoot.sh $cmd $@
		else
			echo "These commands are only valid inside the root of a jail created by jailTools"
			exit 1
		fi
	;;

	daemon)
		if [ "$1" = "" ]; then
			jPath="."
		else
			jPath="$1"
		fi

		if detectJail $jPath; then
			($jailToolsPath/busybox/busybox nohup $sh $jPath/startRoot.sh 'daemon' 2>&1 > $jPath/run/daemon.log) &
			#if [ "$?" != "0" ]; then echo "There was an error starting the daemon, it may already be running."; fi
		else
			echo "These commands are only valid inside the root of a jail created by jailTools"
			exit 1
		fi
	;;

	upgrade)
		if [ "$1" = "" ]; then
			jPath="."
		else
			jPath="$1"
		fi

		if detectJail $jPath; then
			. $jailToolsPath/scripts/jailUpgrade.sh
			startUpgrade $@
		else
			echo "These commands are only valid inside the root of a jail created by jailTools"
			exit 1
		fi
	;;

	*)
		echo "Invalid command \`$cmd'"
		exit 1
	;;
esac

exit 0
